spring:
  profiles:
    active: development
---
spring:
  profiles: development
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
# The OAuth2 server definition that would be used to send the authorization requests to
authserver:
    hostname: localhost
    port: 8899
    contextPath: userauth

# Note that the "/user" endpoint needs to provide the principle of the logged in user (/me endpoint)
security:
  oauth2:
    resource: 
      userInfoUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/me
      preferTokenInfo: false 

datasource:
  postgresql:
    url: jdbc:postgresql://localhost:5432/e2open
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    validation-query: select 1
  openedge:  
    url: jdbc:datadirect:openedge://c217u083.cg.na.jci.com:12700;DatabaseName=symix
    username: E2Open
    password: nepO2E01
    driver-class-name: com.ddtek.jdbc.openedge.OpenEdgeDriver
    validation-query: select 1

logging:
  level:
    org.springframework: INFO
    com.jci: DEBUG  
---
spring:
  profiles: cloud
server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
# The OAuth2 server definition that would be used to send the authorization requests to
authserver:
    hostname: localhost
    port: 8899
    contextPath: userauth

# Note that the "/user" endpoint needs to provide the principle of the logged in user (/me endpoint)
security:
  oauth2:
    resource: 
      userInfoUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/me
      preferTokenInfo: false 
